fix: cicd and title website

diff --git a/.github/workflows/continuous-deployment.yml b/.github/workflows/continuous-deployment.yml
--- a/.github/workflows/continuous-deployment.yml
+++ b/.github/workflows/continuous-deployment.yml
@@ -38,7 +38,7 @@ jobs:
           scp  -o StrictHostKeyChecking=no -r archive/i-mader-landing-page.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/i-mader-landing-page
           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
             cd /root/i-mader-landing-page
-            tar -xzf i-mader-lending-page.tar.gz
+            tar -xzf ~/i-mader-landing-page/i-mader-lending-page.tar.gz
             rm i-mader-lending-page.tar.gz
             echo '** files extracted **'          
             echo "** restarting service tof apply new version **"
@@ -46,8 +46,25 @@ jobs:
             npm install
             npm run build
 
-            pm2 start npm --name "i-mader.tech" -- start
+            # Check if the process "i-mader.tech" is already running
+            pm2 describe i-mader.tech > /dev/null
+                    
+            # Get the exit status of the last command
+            PROCESS_STATUS=$?
+                    
+            # If the process is running, restart it; otherwise, start it
+            if [ $PROCESS_STATUS -eq 0 ]; then
+                echo "Restarting i-mader.tech..."
+                pm2 restart i-mader.tech
+            else
+                echo "Starting i-mader.tech..."
+                pm2 start npm --name "i-mader.tech" -- start
+            fi
+                    
+            # Save the PM2 process list
             pm2 save
+                    
+            # Set up PM2 to start on system boot
             pm2 startup systemd
             echo "** service started **"
           " || exit 1
